### ISSUE TITLE
AK15 Softdrop Mass Correction

### ISSUE THREAD

**Issue by mcremone** [LPC-DM/decaf#34]
To be added.

**Comment by mcremone** [comment]
From Panda:

- how it’s applied, https://github.com/PandaPhysics/PandaAnalysis/blob/tmpnew/Flat/src/FatJetsOps.cc#L184-L201
- histograms that store the corrections, https://github.com/sidnarayanan/PandaAnalysis/blob/a9454df901702fe7bff8e3ac89d364f24e93f71d/Flat/src/HRAnalyzer.cc#L19-L22
- rootfile where histograms are saved, https://github.com/sidnarayanan/PandaAnalysis/blob/master/data/puppiCorr.root

**Comment by mcremone** [comment]
Talked with Nick, these are the same corrections that both ggHbb and boosted Z' analyses are using. They are described in HIG-19-003: 

http://cms.cern.ch/iCMS/jsp/db_notes/noteInfo.jsp?cmsnoteid=CMS%20AN-2018/067 (page 20 of the v11 note)

**Comment by mcremone** [comment]
Also, minimum soft-drop mass appear to be 40 GeV for the ggHbb/boostedZ' guys

**Comment by fdolek** [comment]
I am having AttributeError  while trying to get values because it is TF1, what is the method for evaluate the function in uproot 

>>> file['puppiJECcorr_gen'].values()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TF1' object has no attribute 'values'

**Comment by areinsvo** [comment]
Are you following the example of the ad-hoc correction and using the dense_lookup from lookup_tools?

**Comment by fdolek** [comment]
I was planning to follow lookup tools, but I'm not quite there yet 
because root file is not structured with TH1 as other correction but TF1
so i cannot get the value by using uproot

**Comment by fdolek** [comment]
>>> import uproot
>>> file = uproot.open("puppiCorr.root")
>>> file.keys()
[b'puppiJECcorr_gen;1', b'fitGEN;1', b'puppiJECcorr_reco_0eta1v3;1', b'puppiJECcorr_reco_1v3eta2v5;1', b'fitRECO;1']
>>> file['puppiJECcorr_gen'].values
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TF1' object has no attribute 'values'

**Comment by mcremone** [comment]
I double checked with Nick, this is the way he implements the same corrections:

https://github.com/nsmith-/coffeandbacon/blob/master/analysis/compile_corrections.py#L87-L95

eventually tf1s are functional form, we can explicitly write the equation, as he is doing.

**Comment by fdolek** [comment]
https://github.com/nsmith-/coffeandbacon/blob/15faddf5a1c66dde6b5b9118536c4afa8472424d/analysis/compile_corrections.py#L84
I was trying to export this value
